simulate_fn: lorenz
z0_range: [-5, 5]
z0_dim: 3
n_trajectories: 10
t_max: 25.0
dt: 0.025
solver_method: DOP853
parameters:
  sigma: 10.0
  rho: 28.0
  beta: 2.6666666667
filename: lorenz.npz
save_dir: data